set_property IOSTANDARD LVCMOS33 [get_ports a1]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports b0]
set_property IOSTANDARD LVCMOS33 [get_ports b1]
set_property IOSTANDARD LVCMOS33 [get_ports g]
set_property IOSTANDARD LVCMOS33 [get_ports r]
set_property IOSTANDARD LVCMOS33 [get_ports a0]
set_property PACKAGE_PIN M13 [get_ports a0]
set_property PACKAGE_PIN R15 [get_ports a1]
set_property PACKAGE_PIN N16 [get_ports r]
set_property PACKAGE_PIN R11 [get_ports g]
set_property PACKAGE_PIN G14 [get_ports b]

set_property PACKAGE_PIN L16 [get_ports b1]
set_property PACKAGE_PIN J15 [get_ports b0]
